name: Publisher

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 7 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Check out current repository
      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Get version
        id: rover-version
        run: |
          VERSION="$(gh release list -R apollographql/rover -L 1 | cut -c2-6)"
          echo "Latest version is $VERSION"
          echo "::set-output name=version::$VERSION"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: version=v${{ steps.rover-version.outputs.version }}
          tags: |
            worksome/rover:latest
            worksome/rover:${{ steps.rover-version.outputs.version }}
